add shellcheck

diff --git a/rtask b/rtask
--- a/rtask
+++ b/rtask
@@ -34,23 +34,39 @@ EOF
 exit 1   
 }
 
-tasksdir=$(gettasksdir)
-[[ -d $tasksdir ]] || mkdir -p $tasksdir 
-pushd $tasksdir > /dev/null 
 
-[[ -z $1 ]] && action="list" || action=$1
-shift 1
-### if the next argument matches a taskid...
-if echo $1 | grep -q -E "^\d+(\.\d+)*$" ; then
-       taskid=$1
-       shift 1
-fi
-
-if ! [[ $action = "add" || $action = "list" ]] ; then 
-    if  ! [[ -v taskid ]]  ; then 
-        usage
+parseargs() {
+    [[ -z $1 ]] && action="list" || action=$1
+    shift 1
+    ### if the next argument matches a taskid...
+    if echo "$1" | grep -q -E "^\d+(\.\d+)*$" ; then
+        taskid="$1"
+        shift 1
+        if ! [[ -d $(taskpath "$taskid") ]] ; then 
+            unset taskid
+            usage
+        fi
     fi
-fi
+
+    if ! [[ $action = "add" || $action = "list" ]] ; then 
+        if  ! [[ -v taskid ]]  ; then 
+            usage
+        fi
+    fi
+    if [[ "$action" = "add" || "$action" = "comment" ]] ; then
+        text="$*"
+    elif [[ "$action" = "priority" ]] ; then
+        priority="$1"
+    elif [[ "$action" = "move" ]] ; then 
+        if echo "$1" | grep -q -E "^\d+(\.\d+)*$" && [[ -d $(taskpath "$1") ]] ; then
+            target="$1"
+        else 
+            echo "No such target" 
+            usage
+        fi
+    fi   
+}
+
 
 main() {
     case $action in 
@@ -61,29 +77,26 @@ main() {
             finish 
             ;;
         move)
-            move $taskid $text
+            move "$taskid" "$target"
             ;;
         add)
-            text="$*"
             add "$text"
             ;;
         list) #
             if [[ -v taskid ]] ; then 
-                details $taskid 
+                details "$taskid" 
             else
                 list 
             fi
             ;;
         priority) #
-            setpriority $taskid $text 
+            setpriority "$taskid" "$priority"
             ;;
         comment) # 
-            text="$*"
             comment "$text"
             ;;
         *)
             usage
-            exit 1
             ;;
     esac    
 }
@@ -97,64 +110,66 @@ main() {
 
 
 finish() {
-    touch $(taskpath $taskid)/complete
+    touch "$(taskpath "$taskid")"/complete
 }
 
 move() {
-    mv $(taskpath $1) $(newtaskpath $2)
-    echo $(taskpath $1)
-    echo $(newtaskpath $2) 
+    mv "$(taskpath "$1")" "$(newtaskpath "$2")"
+    echo "moving task"
+    # echo "$(taskpath "$1")"
+    # echo "$(newtaskpath "$2")"
 }
 details() {
-    path=$(taskpath $taskid)
+    path=$(taskpath "$taskid")
     if [[ -e $path/complete ]] ; then echo -n "DONE: " ; fi
-    if [[ -e $path/task ]] ; then cat $path/task ; fi
-    if [[ -d $path/comments ]] ; then cat $path/comments/* ; fi
-    if [[ -e $path/priority ]] ; then echo -n "P " ; cat $path/priority ; else echo "P 0" ; fi
+    if [[ -e $path/task ]] ; then echo -n "TASK: " ; cat "$path"/task ; fi
+    if [[ -d $path/comments ]] ; then echo "COMMENTS" ; cat "$path"/comments/* ; fi
+    if [[ -e $path/priority ]] ; then echo -n "P " ; cat "$path"/priority ; else echo "P 0" ; fi
 }
 
 list() {
-    tasklist=$(for f in $(find . -name task) ; do td=$(dirname $f) ; if [[ -e $td/priority ]] ; then p=$(cat $td/priority) ; else p=0 ; fi ; echo "$p $f" ; done | sort -k1,1nr -k2,2n | cut -f 2- -d ' ')
+    tasklist=$(for f in $(find . -name task) ; do td=$(dirname "$f") ; if [[ -e $td/priority ]] ; then p=$(cat "$td"/priority) ; else p=0 ; fi ; echo "$p $f" ; done | sort -k1,1nr -k2,2n | cut -f 2- -d ' ')
+    # tasklist=$(for f in $(find . -name task) ; do td=$(dirname $f) ; if [[ -e $td/priority ]] ; then p=$(cat $td/priority) ; else p=0 ; fi ; echo "$p $f" ; done | sort -k1,1nr -k2,2n | cut -f 2- -d ' ')
     # tasklist=$(find . -name task | sort -n)
     for f in $tasklist ; do
-        taskdir="$(dirname $f)"
+        taskdir="$(dirname "$f")"
         if [[ -e $taskdir/complete ]] ; then
             continue
         fi
-        taskfile=$(taskid $f)
-        comments=$(getcommentcount $f)
+        taskfile=$(taskid "$f")
+        comments=$(getcommentcount "$f")
         echo -n "$taskfile: "
         if [[ $comments -ne 0 ]] ; then
             echo -n "($comments) "
         fi
-	    cat $f
+	    cat "$f"
     done
 }
 
 add() {
-    path=$(newtaskpath $taskid)
-    mkdir -p $path
-    [[ -z $text ]] && ${EDITOR:=vim} $path/task || echo "$text" > ${path}/task
+    path=$(newtaskpath "$taskid")
+    mkdir -p "$path"
+    [[ -z $text ]] && ${EDITOR:=vim} "$path"/task || echo "$text" > "${path}"/task
 }
 
 comment() {
-    path=$(newcommentpath $taskid)
-    mkdir -p $(dirname $path)
-    [[ -z $* ]] && ${EDITOR:=vim} $path || echo $* > $path
+    path=$(newcommentpath "$taskid")
+    mkdir -p "$(dirname "$path")"
+    [[ -z $* ]] && ${EDITOR:=vim} "$path" || echo "$@" > "$path"
 }
 
 edit() {
-    ${EDITOR:=vim} $(taskpath $taskid)/task
+    ${EDITOR:=vim} "$(taskpath "$taskid")"/task
 }
 
 setpriority() {
-    path=$(taskpath $taskid)/priority
-    echo $2 > $path
+    path=$(taskpath "$taskid")/priority
+    echo "$2" > "$path"
 }
 
 ###########################################################
 #
-# Utitlities
+# Utilities
 #
 ###########################################################
 
@@ -166,93 +181,100 @@ gettasksdir() {
         fi
         RTASKDIR=$XDG_DATA_HOME/tasks
     fi
-    echo $RTASKDIR
+    echo "$RTASKDIR"
 }
 
 taskid() {
     local path=$1
-    if echo $path | grep -q tasks ; then 
-        id=$(echo $path | sed -e 's!^\./!!g' | sed -e 's!/tasks/!.!g' | sed -e 's!/task$!!')
+    if echo "$path" | grep -q tasks ; then 
+        id=$(echo "$path" | sed -e 's!^\./!!g' | sed -e 's!/tasks/!.!g' | sed -e 's!/task$!!')
     else
-        id=$(echo $path | sed -e  's!^\./!!g' | sed -e 's!/!!g' | sed -e 's!task$!!')
+        id=$(echo "$path" | sed -e  's!^\./!!g' | sed -e 's!/!!g' | sed -e 's!task$!!')
     fi
-    echo $id
+    echo "$id"
 }
 
 taskpath()  {
-    if [[ -z $1 ]] ; then 
+    if [[ -z "$1" ]] ; then 
         path="."
     else 
-        local id=$1
-        if echo $id | grep -q "\." ; then
+        local id="$1"
+        if echo "$id" | grep -q "\." ; then
             path=""
             pathsep="/tasks/"
             array=${id//./ }  
-            for e in $(echo $array) ; do 
-                path=$(echo $path$e$pathsep)
+            for e in $array ; do 
+                path="$path""$e"$pathsep
             done 
             # take the last pathsep off
-            path=$(echo $path | sed -e 's!/tasks/$!!')
+            path=${path%%"$pathsep"}
         else 
             path=$id
         fi
     fi
-    echo $path
+    echo "$path"
 }
 
 getcommentcount() {
-    comment_str=""
-    taskdir="$(dirname $1)"
-    comment_count=$(ls $taskdir/comments/ 2>/dev/null | wc -l)
-    comment_int=$(($comment_count+0))
+    taskdir="$(dirname "$1")"
+    comment_count=$(ls "$taskdir"/comments/ 2>/dev/null | wc -l)
+    comment_int=$((comment_count+0))
     echo $comment_int
 }
 
 findnewid() {
-    if [[ $1 == "comment" ]] ; then 
+    if [[ "$1" == "comment" ]] ; then 
         dir="comments"
         shift 1 
     else
         dir="tasks"
     fi
-    if [[ -z $1 ]] ; then
+    if [[ -z "$1" ]] ; then
         path="."
     else
-        if ! [[ -d $(taskpath $1) ]] ; then 
+        if ! [[ -d $(taskpath "$1") ]] ; then 
             error="No such taskID"
         else
-            path=$(taskpath $1)/$dir
+            path=$(taskpath "$1")/$dir
         fi
     fi
     lastid=$(ls $path 2>/dev/null | grep "^[0-9]*$" | wc -l)
-    newid=$(($lastid+1))
+    newid=$((lastid+1))
     if [[ -v error ]] ; then 
-        echo $error
+        echo "$error"
     else 
-        echo $newid
+        echo "$newid"
     fi
 }
 
 newtaskpath() {
-    newid=$(findnewid $1)
-    if [[ $newid = "No such taskID" ]] ; then echo $newid ; exit 1 ; fi
+    newid=$(findnewid "$1")
+    if [[ $newid = "No such taskID" ]] ; then echo "$newid" ; exit 1 ; fi
     if [[ -z $1 ]] ; then 
-        path=$(taskpath $1)
+        path=$(taskpath "$1")
     else
-        path=$(taskpath $1)/tasks 
+        path=$(taskpath "$1")/tasks 
     fi
-    echo $path/$newid
+    echo "$path"/"$newid"
 }
 
 newcommentpath() {
-    newid=$(findnewid comment $1)
-    if [[ $newid = "No such taskID" ]] ; then echo $newid ; exit 1 ; fi
-    if [[ -z $1 ]] ; then 
-        path=$(taskpath $1)
+    newid=$(findnewid comment "$1")
+    if [[ $newid = "No such taskID" ]] ; then echo "$newid" ; exit 1 ; fi
+    if [[ -z "$1" ]] ; then 
+        path=$(taskpath "$1")
     else
-        path=$(taskpath $1)/comments
+        path=$(taskpath "$1")/comments
     fi
-    echo $path/$newid
+    echo "$path"/"$newid"
 }
 
+initdir() {
+    tasksdir=$(gettasksdir)
+    [[ -d $tasksdir ]] || mkdir -p "$tasksdir"
+    pushd "$tasksdir" > /dev/null || exit
+}
+
+initdir
+parseargs "$@" 
 main
